AtkinsRealis_Asset_Manager/AtkinsRealis_Asset_Manager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('Library.urls')),
    path('admin/', admin.site.urls),
]

AtkinsRealis_Asset_Manager/Library/urls.py
from django.urls import path
from django.contrib import admin
from . import views

# Create your urls here.

urlpatterns = [
    # User URLs
    path('', views.default, name='default'),
    path('login/', views.login_request, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_request, name='logout'),
    path('confirm_logout/', views.confirm_logout, name='confirm_logout'),
    path('home_page/', views.home, name='home'),
    path('create_user/', views.create_user, name='create_user'),
    path('delete_user/<str:email>/', views.delete_user, name='delete_user'),
    path('user_info/', views.user_info, name='user_info'),
    path('lockout_timer/', views.lockout_timer_view, name='lockout_timer'),
    path('user_update/<str:username>/', views.user_update, name='user_update'),
    path('user_manage/', views.user_page, name='user_page'),
    
    # Booking URLs
    path('booking_page/', views.booking_page, name='booking_page'),
    path('booking_update/<str:booking_id>/', views.booking_update, name='booking_update'),
    path('new_booking/', views.create_booking, name='create_booking'),
    path('booking_delete/<str:booking_id>/', views.booking_delete, name='booking_delete'),
]

AtkinsRealis_Asset_Manager/Library/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.auth.models import Group, Permission
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

class CustomUserManager(BaseUserManager):
    # Custom user manager model
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff_linked=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    # Custom inputs for User
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    job_title = models.CharField(max_length=100)
    password_creation_date = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    # Custom related names for groups and user_permissions
    groups = models.ManyToManyField(Group, related_name='custom_users')
    user_permissions = models.ManyToManyField(Permission, related_name='custom_users')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['firstname', 'lastname', 'job_title']

    objects = CustomUserManager()

    def __str__(self):
        return self.email

class AssetBooking(models.Model):
    #  Asset Booking Model
    # Options for asset_category
    BOOKING_ID_CHOICES = (
        ('CAM', 'Camera'),
        ('LAS', 'Laser Scanner'),
        ('VRH', 'VR Headset'),
        ('ARH', 'AR Headset'),
        ('ROB', 'Robot'),
    )

    # Custom inputs for bookings
    booking_id = models.AutoField(primary_key=True)
    booked_by = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING, related_name='bookings_as_booked_by', null=True, default='')
    asset_category = models.CharField(max_length=3, choices=BOOKING_ID_CHOICES)
    asset_name = models.CharField(max_length=100)
    asset_id = models.CharField(max_length=100)
    project_name = models.CharField(max_length=255)
    project_number = models.CharField(max_length=20)
    project_manager = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING, null=True, default='')
    date_booked_for = models.DateField()
    approved = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        # Logic to automatically fill asset_id based on the selected asset category and name
        if not self.asset_id:  # Only fill if not already set
            self.asset_id = f"{self.asset_category}-{self.asset_name}"  # Example logic, adjust as needed
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Booking ID: {self.booking_id}, Asset: {self.asset_name}, Project: {self.project_name}"

AtkinsRealis_Asset_Manager/Library/views.py
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.admin.views.decorators import user_passes_test
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import requires_csrf_token
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.db import transaction
from django.db.models import Q
from django.utils import timezone
from .forms import LoginForm, CustomUserForm, CustomUserCreationForm, AssetBookingForm
from .models import CustomUser, AssetBooking

# Create your views here.

@login_required
def default(request):
    """
    Redirects authenticated users to the login page.
    """
    return redirect('login')


@login_required
def home(request):
    """
    Renders the home page for authenticated users.
    """
    return render(request, "home.html")

@login_required
def user_page(request):
    """
    Renders the user management page with all users, hiding their passwords.
    """
    # Fetch all users from CustomUser model
    myusers = CustomUser.objects.all().values()

    # Hides all passwords as 12 x *
    for user in myusers:
        user['password'] = '*' * 12

    context = { 
        "myusers": myusers,
    } 
    # Renders user_page page with all users
    return render(request, "user_manage.html", context)

@login_required
def create_user(request):
    """
    Handles user creation via a form submission.
    """
    # Checks the form submitted on the create_user page
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            with transaction.atomic():
                # Save User in CustomUser Model
                CustomUserSave = form.save()
                messages.success(request, 'User created successfully.')
                # Redirect to user_page on successful submission
                return redirect('user_page')
        else:
            messages.error(request, 'Error creating user. Please check the form.')
    else:
        form = CustomUserCreationForm()
    
    return render(request, 'create_user.html', {'form': form, 'error_messages': messages.get_messages(request)})

@login_required
def delete_user(request, email):
    """
    Deletes a user and updates associated bookings.
    """
    # Get the user object or return a 404 error if not found
    user = get_object_or_404(CustomUser, email=email)
    
    if not request.user.is_staff:
        messages.error(request, 'Sorry, you do not have permissions to do that.')
        return redirect('user_page')

    if request.method == 'POST':
        # Update email to empty string for associated bookings where the user is referenced
        AssetBooking.objects.filter(Q(booked_by=user) | Q(project_manager=user)).update(
            booked_by=None, 
            project_manager=None
        )

        # Now delete the user itself
        user.delete()

        messages.success(request, 'User deleted successfully.')
        return redirect('user_page')

    # Render a confirmation page for GET requests
    return render(request, 'confirm_delete.html', {'user': user})

@login_required
def user_info(request):
    """
    Renders the user information page and handles updates to user information.
    """
    # Renders the user page 
    user = request.user
    try:
        custom_user = CustomUser.objects.get(email=user)
        if request.method == 'POST':
            form = CustomUserForm(request.POST, instance=custom_user)
            if form.is_valid():
                form.save()
                messages.success(request, 'User information updated successfully.')
                return redirect('user_page')  # Redirect to the same page after successful update
            else:
                messages.error(request, 'Error updating user information. Please check the form.')
        else:
            form = CustomUserForm(instance=custom_user)  # Pass the user instance to prepopulate the form fields
    except CustomUser.DoesNotExist:
        messages.error(request, 'User not found.')
        return redirect('user_page')

    return render(request, 'user_info.html', {'form': form, 'error_messages': messages.get_messages(request)})

@login_required
def user_update(request, username):
    """
    Updates user information for a specified user.
    """
    # Checks to see if the user is_staff and can update the user
    if not request.user.is_staff:
        messages.error(request, 'Sorry, you do not have permissions to do that.')
        return redirect('user_page')
    
    # Get the user object or return a 404 error if not found
    user = get_object_or_404(CustomUser, email=username)

    if request.method == 'POST':
        form = CustomUserForm(request.POST, instance=user)
        if form.is_valid():
            password = form.cleaned_data.get('password')

            if password:
                try:
                    validate_password(password)
                except ValidationError as e:
                    form.add_error('password', e)  # Add validation error to the password field
                    messages.error(request, 'Your password must be between 8-20 characters and include at least one special character.')
                    return render(request, 'user_info.html', {'form': form, 'error_messages': messages.get_messages(request)})
            
            form.save()
            messages.success(request, 'User information updated successfully.')
            return redirect('user_page')  # Redirect to the same page after successful update
        else:
            messages.error(request, 'Error updating user information. Please check the form.')
    else:
        form = CustomUserForm(instance=user)  # Pass the user instance to prepopulate the form fields

    return render(request, 'user_info.html', {'form': form, 'error_messages': messages.get_messages(request)})

@login_required
def booking_page(request):
    """
    Renders the bookings management page with all bookings and users.
    """
    # Fetch all bookings from AssetBooking model
    mybookings = AssetBooking.objects.all().values()
    myusers = CustomUser.objects.all().values()

    context = { 
        "mybookings": mybookings,
        "myusers": myusers
    } 
    return render(request, "bookings_manage.html", context)

@requires_csrf_token
def custom_csrf_failure_view(request, reason=""):
    """
    Custom view for handling CSRF failures.
    """
    return render(request, '403_csrf.html', status=403)

@login_required
def create_booking(request):
    """
    Handles the creation of a new booking.
    """
    # Renders the create_booking FORM to booking_page URL
    if request.method == 'POST':
        form = AssetBookingForm(request.POST)
        if form.is_valid():
            messages.success(request, 'New booking created successfully.')
            form.save()
            # Redirect to booking_page URL
            return redirect('booking_page')
        else:
            messages.error(request, 'Error creating new booking. Please check the form.')
            print("Form is invalid:", form.errors)  # Print form errors for debugging
    else:
        form = AssetBookingForm()
    
    return render(request, 'new_booking.html', {'form': form})

@login_required
def booking_update(request, booking_id):
    """
    Updates booking information for a specified booking.
    """
    # Renders the booking update page
    existing_booking = get_object_or_404(AssetBooking, booking_id=booking_id)

    # Checks the submitted form
    if request.method == 'POST':
        form = AssetBookingForm(request.POST, instance=existing_booking)
        if form.is_valid():
            form.save()
            messages.success(request, 'Booking information updated successfully.')
            return redirect('booking_page')  # Redirect to the same page after successful update
        else:
            messages.error(request, 'Error updating booking information. Please check the form.')
    else:
        form = AssetBookingForm(instance=existing_booking)  # Pass the booking instance to prepopulate the form fields

    return render(request, 'booking_info.html', {'form': form, 'error_messages': messages.get_messages(request)})

@login_required
def booking_delete(request, booking_id):
    """
    Deletes a booking.
    """
    # Get the booking object or return a 404 error if not found
    booking = get_object_or_404(AssetBooking, booking_id=booking_id)
    
    if not request.user.is_staff:
        messages.error(request, 'Sorry, you do not have permissions to do that.')
        return redirect('booking_page')

    if request.method == 'POST':
        # Delete instances from AssetBooking where the booking_id is referenced
        AssetBooking.objects.filter(booking_id=booking_id).delete()
        
        messages.success(request, 'Booking deleted successfully.')
        return redirect('booking_page')

    # Render a confirmation page for GET requests
    return render(request, 'confirm_delete_booking.html', {'booking': booking})

def login_request(request):
    """
    Handles user login.
    """
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate_custom_user(email=email, password=password)
            ip = get_client_ip(request)
            key = f'failed_login_attempts_{ip}'
            attempts, first_attempt_time = cache.get(key, (0, None))
            

AtkinsRealis_Asset_Manager/Library/templates/403_csrf.html
{% extends "master.html" %}

{% block title_1 %}
    Forbidden (403)
{% endblock %}

{% block content %}
    <body>
        <div class="welcome-message">
            <h1>Forbidden (403)</h1>
            <p>CSRF verification failed. Request aborted.</p>
            <p>Please try again or contact support if the issue persists.</p>
        </div>
    </body>
{% endblock %}

AtkinsRealis_Asset_Manager/Library/templates/booking_info.html
{% extends "master.html" %}

{% block title_1 %}
    Modify Booking
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Modify Existing Booking</h2>
        <form method="post" class="forms">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_booked_by" class="form-label">Booked By:</label>
                {{ form.booked_by }}
            </div>
            <div class="form-group">
                <label for="id_asset_category" class="form-label">Asset Category:</label>
                {{ form.asset_category }}
            </div>
            <div class="form-group">
                <label for="id_asset_name" class="form-label">Asset Name:</label>
                {{ form.asset_name }}
            </div>
            <div class="form-group">
                <label for="id_project_name" class="form-label">Project Name:</label>
                {{ form.project_name }}
            </div>
            <div class="form-group">
                <label for="id_project_number" class="form-label">Project Number:</label>
                {{ form.project_number }}
            </div>
            <div class="form-group">
                <label for="id_project_manager" class="form-label">Project Manager:</label>
                {{ form.project_manager }}
            </div>
            <div class="form-group">
                <label for="id_date_booked_for" class="form-label">Date Booked For (YYYY-MM-DD):</label>
                {{ form.date_booked_for }}
            </div>
            {% if request.user.is_staff %}
            <div class="form-group">
                <label for="id_approved" class="form-label">Approved:</label>
                {{ form.approved }}
            </div>
            {% endif %}
            <button type="submit" class="btn btn-primary">Update Booking</button>
            <div class="form-group"></div>
            <button type="button" onclick="goBack()">Go Back</button>
        </form>
        <div id="error-message" class="error-message" style="display: none;"></div>
    </div>
{% endblock %}

AtkinsRealis_Asset_Manager/Library/templates/bookings_manage.html
{% extends "master.html" %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title_1 %}Booking's Manager{% endblock %}</title>
</head>
<body>
    {% block content %}
    <div class="button-container1">
        <a href="/new_booking/" class="button">New Booking</a>
    </div>
    <h1>Booking List</h1>
    <div class="table-container">
        <table class="table">
            <tr>
                <th style="min-width: 150px;">Booking ID:</th>
                <th style="min-width: 150px;">Booked By:</th>
                <th style="min-width: 150px;">Asset Category:</th>
                <th style="min-width: 150px;">Asset Name:</th>
                <th style="min-width: 150px;">Asset ID:</th>
                <th style="min-width: 250px;">Project Name:</th>
                <th style="min-width: 200px;">Project Manager:</th>
                <th style="min-width: 150px;">Date Booked For:</th>
                <th style="min-width: 150px;">Approved:</th>
                <th style="min-width: 150px;">Update:</th>
                {% if request.user.is_staff %}
                <th style="min-width: 150px;">Delete:</th>
                {% endif %}
            </tr>
            {% for booking in mybookings %}
            <tr>
                <td>{{ booking.booking_id }}</td>
                <td>
                    {% for user in myusers %}
                        {% if user.id == booking.booked_by_id %}
                            {{ user.username }}
                        {% endif %}
                    {% endfor %}
                </td>
                <td>{{ booking.asset_category }}</td>
                <td>{{ booking.asset_name }}</td>
                <td>{{ booking.asset_id }}</td>
                <td>{{ booking.project_name }}</td>
                <td>
                    {% for user in myusers %}
                        {% if user.id == booking.project_manager_id %}
                            {{ user.username }}
                        {% endif %}
                    {% endfor %}
                </td>
                <td>{{ booking.date_booked_for }}</td>
                <td>{{ booking.approved }}</td>
                <td>
                    <form action="{% url 'booking_update' booking.booking_id %}">
                        {% csrf_token %}
                        <button type="submit" class="button1">Update</button>
                    </form>
                </td>
                {% if request.user.is_staff %}
                <td>
                    <form method="get" action="{% url 'booking_delete' booking.booking_id %}">
                        {% csrf_token %}
                        <button type="submit" class="button1">Delete</button>
                    </form>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>
    {% endblock %}
</body>
</html>

AtkinsRealis_Asset_Manager/Library/templates/confirm_delete.html
{% extends 'master.html' %}

<head>
    <title>{% block title_1 %}Confirm Deletion{% endblock %}</title>
</head>

{% block content %}
<div>
    <main class="content">
        <h1>Are you sure you want to delete {{ user.email }}?</h1>
        <form method="post">
            {% csrf_token %}
            <div class="button-container">
                <button type="submit" class="button2">Yes</button>
                <a href="{% url 'user_page' %}" class="button2">No</a>
            </div>
        </form>
    </main>
</div>
{% endblock %}

AtkinsRealis_Asset_Manager/Library/templates/confirm_delete_booking.html
{% extends 'master.html' %}

<head>
  <title>{% block title_1 %}Confirm Deletion{% endblock %}</title>
</head>

{% block content %}
<div>
    <main class="content">
        <h1>Are you sure you want to delete this booking?</h1>
        <form method="post">
            {% csrf_token %}
            <div class="button-container">
                <button type="submit" class="button2">Yes</button>
                <a href="{% url 'booking_page' %}" class="button2">No</a>
            </div>
        </form>
    </main>
</div>
{% endblock %}

AtkinsRealis_Asset_Manager/Library/templates/confirm_logout.html
{% extends 'master.html' %}

<head>
    <title>{% block title_1 %}Confirm Log Out{% endblock %}</title>
</head>

{% block content %}
<div>
    <main class="content">
        <h1>Are you sure you want to log out?</h1>
        <form method="post">
            {% csrf_token %}
            <div class="button-container">
                <button type="submit" class="button2">Yes</button>
                <button type="button" class="button2" onclick="window.history.back();">No</button>
            </div>
        </form>
    </main>
</div>
{% endblock %}

AtkinsRealis_Asset_Manager/Library/templates/create_user.html
{% extends "master.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_1 %}Create User{% endblock %}</title>
    <style>
        .button {
            width: 100%;
            padding: 10px;
            background-color: #192d38;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            transition: background-color 0.3s ease;
        }

        .button:hover {
            background-color: #0f1e26; /* Adjust the hover color if needed */
        }

        .button-container1 {
            display: flex;
            gap: 10px; /* Adjust the gap between buttons as needed */
        }
    </style>
</head>
<body>
    {% block content %}
    <div class="container">
        <h2>Create User</h2>
        <form method="post" class="forms">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="form-label">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="email" class="form-label">Email:</label>
                <input type="text" id="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="firstname" class="form-label">First Name:</label>
                <input type="text" id="firstname" name="firstname" required>
            </div>
            <div class="form-group">
                <label for="lastname" class="form-label">Last Name:</label>
                <input type="text" id="lastname" name="lastname" required>
            </div>
            <div class="form-group">
                <label for="job_title" class="form-label">Job Title:</label>
                <input type="text" id="job_title" name="job_title" required>
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Password:</label>
                <input type="text" id="password" name="password" required>
            </div>
            {% if request.user.is_staff %}
            <div class="form-group">
                <label for="is_staff" class="form-label">Admin:</label>
                <input type="checkbox" id="is_staff" name="is_staff" {% if form.instance.is_staff %}checked{% endif %}>
            </div>
            {% endif %}
            <button type="submit" class="button1">Create User</button>
            <div class="form-group"></div>
            <button type="button" class="button1" onclick="goBack()">Go Back</button>
        </form>
        <div id="error-message" class="error-message" style="display: none;"></div>
    </div>
    {% endblock %}
</body>
</html>

AtkinsRealis_Asset_Manager/Library/templates/home.html
{% extends "master.html" %}

<!DOCTYPE html>
<html>
    
<head>
    <title>{% block title_1 %}Home Page{% endblock %}</title>
</head>

<body>
    {% block content %}
    <div class="welcome-message">
        <h1>Welcome to the AtkinsRéalis Asset Booking System</h1>
        <p>Please select an option below:</p>
    </div>  
    <div class="button-container1">
        <a href="/user_manage/" class="button">User Manager</a>
        <a href="/booking_page/" class="button">Asset Booking</a>
    </div>
    {% endblock %}
</body>

AtkinsRealis_Asset_Manager/Library/templates/lockout.html
{% extends "master.html" %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title_1 %}Account Locked{% endblock %}s</title>
</head>
{% block content %}
<body>
    <div class="welcome-message">
    <h1>Your account is locked</h1>
    <div class="welcome-message"></div>
    <p>You have been locked out due to too many failed login attempts. Please wait <span id="timer" style="font-weight: bold;">{{ lockout_time }}</span> seconds before trying again.</p>
    </body>
{% endblock %}
</html>

AtkinsRealis_Asset_Manager/Library/templates/login_page.html
{% extends "master.html" %}

<!DOCTYPE html>
<html>
    
<head>
    <title>{% block title_1 %}Login Page{% endblock %}</title>
</head>


{% block content %}
</head>
<body>
    <div class="login-container">
        {% if error_message %}
            <p class="error-message">{{ error_message }}</p>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <h1>Login</h1>
            <label for="id_username">Email</label>
            {{ form.username }}
            <label for="id_password">Password</label>
            {{ form.password }}
            <div>
                <input type="submit" value="Login" class="button2">
            </div>
        </form>
        <div class="login-link">
            <p>Don't have an account? <a href="/register/">Register here</a>.</p>
        </div>
    </div>
</body>
{% endblock %}
</html>

AtkinsRealis_Asset_Manager/Library/templates/new_booking.html
{% extends "master.html" %}

{% block title_1 %}
    Create Asset Booking
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Create Asset Booking</h2>
        <form method="post" class="forms">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_booked_by" class="form-label">Booked By:</label>
                {{ form.booked_by }}
            </div>
            <div class="form-group">
                <label for="id_asset_category" class="form-label">Asset Category:</label>
                {{ form.asset_category }}
            </div>
            <div class="form-group">
                <label for="id_asset_name" class="form-label">Asset Name:</label>
                {{ form.asset_name }}
            </div>
            <div class="form-group">
                <label for="id_project_name" class="form-label">Project Name:</label>
                {{ form.project_name }}
            </div>
            <div class="form-group">
                <label for="id_project_number" class="form-label">Project Number:</label>
                {{ form.project_number }}
            </div>
            <div class="form-group">
                <label for="id_project_manager" class="form-label">Project Manager:</label>
                {{ form.project_manager }}
            </div>
            <div class="form-group">
                <label for="id_date_booked_for" class="form-label">Date Booked For (YYYY-MM-DD):</label>
                {{ form.date_booked_for }}
            </div>
            {% if request.user.is_staff %}
            <div class="form-group">
                <label for="id_approved" class="form-label">Approved:</label>
                {{ form.approved }}
            </div>
            {% endif %}
            <button type="submit" class="button1">Create Asset Booking</button>
            <div class="form-group"></div>
            <button type="button" class="button1" onclick="goBack()">Go Back</button>
        </form>
        <div id="error-message" class="error-message" style="display: none;"></div>
    </div>
{% endblock %}